### ISSUE TITLE
Remove sh python dependency

### ISSUE THREAD

**Issue by BrennanGit** [xmos/audio_test_tools#188]
The "sh" python dependency can be replaced with subprocess in all cases that we've seen so far.
This enables this library to be used on windows.
Example of similar change here: https://github.com/xmos/xscope_fileio/pull/13

**Comment by mbanth** [comment]
@danielpieczko, can you fit the work for this issue into your schedule without disrupting your other assignments?  I do not want to delay your work on USB Audio, so please let me know if adding this issue to your list will cause a problem.  Thanks.

**Comment by danielpieczko** [comment]
Done in #189
